name: Build App FE Main

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Setup
        uses: actions/checkout@v3

      - name: .env setting
        run: |
          echo "VITE_ACCESS_KEY=${{ secrets.VITE_ACCESS_KEY }}" >> .env
          echo "VITE_SECRET_KEY=${{ secrets.VITE_SECRET_KEY }}" >> .env
      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Package Install
        run: yarn install

      - name: Project Build
        run: yarn build

      # GitHub Actions CLI 환경에서 S3 사용자 권한의 aws 접속
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Vue 빌드한 /build를 s3로 업로드
      - name: Upload /build to S3
        run: aws s3 cp --recursive --region ${{ secrets.AWS_DEFAULT_REGION }} dist s3://${{ secrets.AWS_BUCKET_NAME_MAIN }}
